name: Sync to Hugging Face Hub
on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and Push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone --depth 1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git repo
          cd repo
          git push --force https://Namantiwariix:$HF_TOKEN@huggingface.co/spaces/Namantiwariix/ATSFixer main:main
